# Carga y Exploración de Archivos CSV con Python

En este tutorial aprenderás a descargar un archivo `.csv` a tu entorno local y a leerlo utilizando la librería pandas de Python.

## ¿Qué es un archivo CSV?

- CSV (Comma-Separated Values): Es un archivo de texto plano donde la información se organiza en filas y se separa mediante comas o delimitadores similares.  
- Uso: Es uno de los formatos más utilizados para representar hojas de cálculo y bases de datos.
- Compatibilidad: Es muy práctico gracias a que la mayoría de programas de análisis pueden leerlo y generar salidas en este formato.

**Paso 1: Descargar el archivo localmente**

Antes de ejecutar el código, asegúrate de descargar el archivo `.csv` a tu computadora y colocarlo dentro de la carpeta de tu proyecto (por ejemplo, en un directorio llamado `data/`).

**Paso 2: Importar la librería Pandas**

Utilizamos la biblioteca pandas para manipular archivos CSV. Pandas maneja una estructura de datos llamada `DataFrame`, la cual convierte los archivos CSV en tablas compuestas por filas y columnas. La primera línea del archivo se transforma en los nombres de las columnas.  Por convención, importamos la librería bajo el alias `pd`.

In [2]:
import pandas as pd

**Paso 3: Leer el archivo CSV descargado**

Para cargar el archivo desde tu directorio local utilizamos la función `.read_csv('ruta/del/archivo.csv')`. Esta función retorna un `DataFrame` que guardaremos en la variable `df`.  Para verificar que la lectura fue exitosa, imprimimos las primeras 5 filas usando `.head()`.

In [3]:
# Reemplaza 'data/estudiantes.csv' por la ruta donde guardaste tu archivo descargado
df = pd.read_csv('simpsons_paradox_covid.csv')
df.head()

   Unnamed: 0 age_group vaccine_status outcome
0           1  under 50     vaccinated   death
1           2  under 50     vaccinated   death
2           3  under 50     vaccinated   death
3           4  under 50     vaccinated   death
4           5  under 50     vaccinated   death

**Paso 4: Visualizar más filas y explorar la estructura**

Por defecto, `.head()` muestra las primeras 5 filas. Si deseas ver un número mayor de registros, puedes pasar el número de filas como argumento, por ejemplo `.head(10)`.

In [4]:
df.head(10)

   Unnamed: 0 age_group vaccine_status outcome
0           1  under 50     vaccinated   death
1           2  under 50     vaccinated   death
2           3  under 50     vaccinated   death
3           4  under 50     vaccinated   death
4           5  under 50     vaccinated   death
5           6  under 50     vaccinated   death
6           7  under 50     vaccinated   death
7           8  under 50     vaccinated   death
8           9  under 50     vaccinated   death
9          10  under 50     vaccinated   death

Para obtener una vista general del conjunto de datos (número total de filas, columnas y tipos de datos), utilizamos la función `.info()`.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 268166 entries, 0 to 268165
Data columns (total 4 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      268166 non-null  int64
 1   age_group       268166 non-null  str
 2   vaccine_status  268166 non-null  str
 3   outcome         268166 non-null  str
dtypes: int64(1), str(3)
memory usage: 8.2 MB

**Paso 5: Guardar modificaciones en un nuevo CSV**

Si deseas exportar los datos a un archivo nuevo, puedes usar `.to_csv('ruta/archivo.csv')`.  

Nota: Si el archivo de destino no existe, se creará uno nuevo; si ya existe, se sobrescribirá.

In [7]:
df.to_csv('simpsons_paradox_covid_new.csv', index=False)

---
## **Ejercicio Práctico: Leer y explorar un dataset descargado**

Descarga el archivo de prueba `data/HELPfull.csv` a la carpeta de tu proyecto y realiza las siguientes tareas:

1. Importa la librería pandas.
2. Lee el archivo descargado usando `pd.read_csv()` y almacénalo en una variable.  
3. Muestra las primeras 5 filas de la tabla.  
4. Imprime las primeras 10 filas de la tabla.  
5. Muestra la información estructural del dataset usando `.info()`.  
6. Exporta una copia del archivo con el nombre `data/HELPfull_nuevo.csv`.

---
# Web Scraping con Python
El web scraping es una técnica automatizada para extraer y recopilar información masiva alojada en sitios web. Funciona mediante programas o scripts que simulan la interacción humana con un navegador para descargar el código HTML de una página y extraer únicamente los datos de interés.

**Paso 1: Descarga de páginas web con Requests**

Para extraer datos de una página web, el primer paso es descargar su contenido HTML. La librería requests realiza una petición HTTP GET al servidor del sitio web. El objeto de respuesta obtenido contiene la propiedad status_code para verificar el éxito de la descarga (un código 200 indica éxito) y la propiedad content que almacena el contenido en bruto.

In [ ]:
import requests

# Descargar el contenido HTML de una página web de prueba
page = requests.get("https://dataquestio.github.io/web-scraping-pages/simple.html")

# Verificar el estado de la petición (200 = Éxito)
print("Código de estado:", page.status_code)

# Mostrar el contenido HTML en bruto
print("\nContenido HTML obtenido:")
print(page.content)

**Paso 2: Parseo y navegación del HTML con BeautifulSoup**

El contenido HTML bruto se debe interpretar mediante un analizador de sintaxis. La librería BeautifulSoup transforma el documento en un árbol de objetos navegables. El método prettify() permite formatear el código para entender la estructura de las etiquetas. Para buscar elementos, usamos find() para obtener la primera ocurrencia o find_all() para recuperar todas las coincidencias de una etiqueta.

In [ ]:
from bs4 import BeautifulSoup

# Crear una instancia de BeautifulSoup para analizar el HTML
soup = BeautifulSoup(page.content, 'html.parser')

# Imprimir la estructura HTML de forma organizada
print("Estructura jerárquica del HTML:")
print(soup.prettify())

# Extraer el primer párrafo <p> del documento y obtener su texto
primer_p = soup.find('p')
print("Texto extraído del párrafo:", primer_p.get_text())

**Paso 3: Búsqueda por clases, identificadores (ID) y selectores CSS**

En sitios reales, las etiquetas HTML incluyen atributos como class o id para definir estilos o identificadores únicos. BeautifulSoup permite filtrar directamente mediante el parámetro class_ o id. Adicionalmente, el método select() acepta selectores CSS para realizar búsquedas complejas entre elementos anidados.

In [ ]:
# Descargar una página con atributos de clase e identificadores
page_ids = requests.get("https://dataquestio.github.io/web-scraping-pages/ids_and_classes.html")
soup_ids = BeautifulSoup(page_ids.content, 'html.parser')

# Buscar todos los elementos <p> que contengan la clase 'outer-text'
p_outer = soup_ids.find_all('p', class_='outer-text')

# Buscar elementos por su ID único
elemento_first = soup_ids.find_all(id="first")

# Usar selectores CSS para obtener párrafos <p> anidados dentro de un <div>
p_en_div = soup_ids.select("div p")

print("Elementos con clase 'outer-text':", [p.get_text().strip() for p in p_outer])
print("Párrafo dentro de div:", [p.get_text().strip() for p in p_en_div])

**Paso 4: Extracción de datos tabulares (Caso práctico: Pronóstico meteorológico)**

Integrando las técnicas anteriores, extraemos la información meteorológica de 7 días emitida por el National Weather Service para Boulder, CO. Identificamos el contenedor general con id="seven-day-forecast" y extraemos en listas paralelas los nombres del periodo, descripciones cortas, temperaturas y descripciones completas.

In [ ]:
import requests
from bs4 import BeautifulSoup

# 1. Petición GET a la página del pronóstico meteorológico
url = "https://forecast.weather.gov/MapClick.php?lat=40.0466&lon=-105.2523#.YwpRBy2B1f0"
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')

# 2. Localizar el elemento contenedor por ID
seven_day = soup.find(id="seven-day-forecast")

# 3. Extraer la información utilizando comprensiones de lista y selectores CSS
periods = [pt.get_text() for pt in seven_day.select(".tombstone-container .period-name")]
short_descs = [sd.get_text() for sd in seven_day.select(".tombstone-container .short-desc")]
temps = [t.get_text() for t in seven_day.select(".tombstone-container .temp")]
descs = [d["title"] for d in seven_day.select(".tombstone-container img")]

print("Periodos extraídos:", periods)
print("Temperaturas extraídas:", temps)

**Paso 5: Estructuración y exportación con Pandas**

Una vez extraídas las listas con la información relevante, se estructuran en una tabla mediante un DataFrame de la librería pandas. Esto facilita la manipulación de datos y su posterior guardado en formatos estándar como CSV mediante el método to_csv().

In [ ]:
import pandas as pd

# Construir el DataFrame utilizando un diccionario de listas
weather = pd.DataFrame({
    "period": periods,
    "short_desc": short_descs,
    "temp": temps,
    "desc": descs
})

# Exportar los datos estructurados a un archivo CSV
weather.to_csv('Boulder_Weather_7_Days.csv', index=False)

# Mostrar los primeros registros del DataFrame
weather.head()

---
## **Ejercicio Práctico:**

Implementa un bloque de código para transformar y filtrar la información del DataFrame weather generado en el paso anterior.

1. Limpieza de datos: Extrae únicamente los valores numéricos enteros de la columna temp y guárdalos en una nueva columna llamada temp_num (por ejemplo, convertir "High: 88 °F" al valor numérico 88).
2. Conversión matemática: Crea una columna llamada temp_celsius que convierta los grados Fahrenheit ($°F$) a grados Celsius ($°C$) utilizando la fórmula:$$°C = (F - 32) \times \frac{5}{9}$$
3. Filtrado de datos: Genera un nuevo DataFrame filtrado que contenga únicamente los periodos donde la temperatura original sea mayor a $87\text{ °F}$.
4. Almacenamiento: Guarda la tabla filtrada en un archivo llamado Boulder_Hot_Days.csv.

---
# Recolección y Análisis de Datos Cinematográficos con TMDB API

Se indica el proceso de autenticación, extracción de datos en tendencia, paginación masiva, recopilación de reseñas para Procesamiento de Lenguaje Natural (NLP) y exportación de datos utilizando la API de The Movie Database (TMDB).

**Paso 1: Importación de librerías y configuración de credenciales**

Carga los módulos fundamentales (`pandas` para la manipulación de tablas, `requests` para gestionar llamadas HTTP y os para acceder al sistema operativo) y almacena el Bearer Token de autenticación en una variable de entorno segura.

In [ ]:
import pandas as pd
import requests
import os
import json

# Configuración del token de acceso de lectura de la API (v3 auth / v4 bearer)
# Registrate gratis en https://www.themoviedb.org/settings/api para obtener tu token
os.environ["TMDB_BEARER_TOKEN"] = "TU_TMDB_BEARER_TOKEN_AQUI"

**Paso 2: Creación de la conexión HTTP**

Define la función encargada de recuperar la clave guardada y construir el encabezado (`Header`) con la clave `Authorization`. Este paso garantiza que cada petición enviada a la API incluya las credenciales necesarias para ser aceptada por los servidores de TMDB.

In [ ]:
def connect_to_api():
    bearer_token = os.environ.get("TMDB_BEARER_TOKEN")
    return {
        "accept": "application/json",
        "Authorization": f"Bearer {bearer_token}"
    }

headers = connect_to_api()
print("Encabezados configurados correctamente.")

**Paso 3: Consulta inicial: Películas en tendencia (Trending)**

Envía una primera solicitud al punto de enlace (endpoint) `/trending/movie/week`. Recibe la respuesta en formato JSON, filtra el objeto de resultados y lo convierte en un `DataFrame` básico para visualizar atributos como el ID, el título, la popularidad y el promedio de votación.

In [ ]:
def get_trending_movies(headers):
    url = "https://api.themoviedb.org/3/trending/movie/week?language=es-ES"
    response = requests.get(url, headers=headers)
    return response.json()

# Petición y transformación
json_data = get_trending_movies(headers)
df_trending = pd.DataFrame(json_data.get('results', []))

# Selección de variables clave
columnas_interes = ['id', 'title', 'release_date', 'vote_average', 'vote_count', 'popularity']
df_trending[columnas_interes].head()

**Paso 4: Extracción masiva con paginación**

Supera la restricción de registros por petición de la API mediante un bucle `for` que itera sobre la variable `page` en el endpoint `/discover/movie`. Extrae progresivamente cientos de filas ordenadas por popularidad, acumulándolas en una lista global para después generar un dataset consolidado.

In [ ]:
def fetch_catalog_pages(headers, total_pages=5):
    all_movies = []
    base_url = "https://api.themoviedb.org/3/discover/movie"

    for page in range(1, total_pages + 1):
        params = {
            "language": "es-ES",
            "sort_by": "popularity.desc",
            "include_adult": "false",
            "page": page
        }
        res = requests.get(base_url, headers=headers, params=params).json()
        if 'results' in res:
            all_movies.extend(res['results'])

    return pd.DataFrame(all_movies)

# Recolección de 5 páginas (~100 registros)
df_catalog = fetch_catalog_pages(headers, total_pages=5)
print(f"Total de películas recolectadas: {len(df_catalog)}")
df_catalog[['id', 'title', 'vote_average', 'popularity']].head()

**Paso 5: Extracción de textos para Análisis de Sentimiento (Reviews)**

Toma los identificadores (`movie_id`) recolectados previamente y consulta el endpoint secundario `/movie/{movie_id}/reviews`. Desestructura la información anidada (autor, calificación, texto) para construir un conjunto de datos plano especializado en tareas de Procesamiento de Lenguaje Natural (NLP).

In [ ]:
def get_movie_reviews(headers, movie_id):
    url = f"https://api.themoviedb.org/3/movie/{movie_id}/reviews?language=en-US"
    res = requests.get(url, headers=headers).json()
    reviews = res.get('results', [])

    # Extraer campos de interés
    parsed_reviews = []
    for r in reviews:
        parsed_reviews.append({
            'movie_id': movie_id,
            'review_id': r.get('id'),
            'author': r.get('author'),
            'rating': r.get('author_details', {}).get('rating'),
            'content': r.get('content'),
            'created_at': r.get('created_at')
        })
    return parsed_reviews

# Recopilar reseñas de las primeras 5 películas recolectadas
all_reviews = []
for m_id in df_catalog['id'].head(5):
    all_reviews.extend(get_movie_reviews(headers, m_id))

df_reviews = pd.DataFrame(all_reviews)
df_reviews[['movie_id', 'author', 'rating', 'content']].head()

**Paso 6: Almacenamiento y exportación de conjuntos de datos**

Verifica o crea la carpeta de destino `/data` en el sistema de archivos local de Colab utilizando `os.makedirs()` y exporta las tablas finales (`df_catalog` y `df_reviews`) a archivos `.csv` listos para ser descargados o analizados.

In [ ]:
# Creación de directorio local y guardado de archivos CSV
os.makedirs('data', exist_ok=True)

df_catalog.to_csv('data/tmdb_movies_catalog.csv', index=False)
df_reviews.to_csv('data/tmdb_movie_reviews.csv', index=False)

print("Archivos exportados exitosamente en la carpeta /data:")
print("- tmdb_movies_catalog.csv")
print("- tmdb_movie_reviews.csv")

## Ejercicio Práctico: Extracción y Análisis Demográfico Global con REST Countries API

El objetivo de este ejercicio es consumir la API pública de REST Countries (que no requiere API Key), transformar la respuesta JSON a un DataFrame de pandas, calcular la densidad poblacional por país y realizar un análisis de agregación por continente.

**Instrucciones para el estudiante:**

1. Importa las librerías requests, pandas y os.
2. Realiza una petición GET al endpoint [https://restcountries.com/v3.1/all](https://restcountries.com/v3.1/all) para obtener el listado global de países.
3. Transforma la respuesta JSON iterando sobre cada país para extraer los siguientes campos:
- Nombre común: name $\rightarrow$ common
- Región/Continente: region
- Población: population
- Superficie (Área en $\text{km}^2$): area
- Capital: capital (extrae el primer elemento de la lista si existe, o asigna "Sin Capital").

4. Construye un DataFrame con la información recolectada.
5. Crea una columna calculada llamada densidad_poblacional dividiendo la poblacion entre el area (hab/$\text{km}^2$).
6. Muestra las primeras 5 filas del dataset.
7. Calcula el promedio de población y de área agrupado por región (region) utilizando .groupby().
8. Identifica los 5 países más densamente poblados con una superficie mayor a 1,000 $\text{km}^2$.
9. Exporta el resultado final a un archivo CSV en la ruta data/paises_mundo.csv.